### ISSUE TITLE
Actual examples, please

### ISSUE THREAD

**Issue by akauppi** [zalando/nakadi-manual#14]
I and some of my colleages are of the opinion that real-world samples are better than artificial ones.

In the case of nakadi-manual, `https://auth.example.com/oauth2/tokeninfo` in https://github.com/zalando/nakadi-manual/blob/master/docs/api-spec-generated/security.md#oauth2 looks artificial. Could we use the proper Zalando URL instead: `https://token.auth.zalando.com/access_token`

**Comment by akauppi** [comment]
Actually, Fabian Wollert gave the right URL `https://info.services.auth.zalando.com/oauth2/tokeninfo` in Hipchat. Will make a PR.

**Comment by dehora** [comment]
reopening until the documentation is updated
