### ISSUE TITLE
API Reference Link broken

### ISSUE THREAD

**Issue by MALPI** [zalando/nakadi-manual#33]
The Link to the "API-Reference" in Section "Creating an event type" leads to [404](http://zalando.github.io/nakadi-manual/docs/using/api-reference.html).

**Comment by lasomethingsomething** [comment]
Hey @MALPI, is this still true? Someone want to fix @dehora @rcillo @v-stepanov @valgog @adyach?

**Comment by MALPI** [comment]
It's finde
