### ISSUE TITLE
Add ContentType header to documentation

### ISSUE THREAD

**Issue by MALPI** [zalando/nakadi-manual#35]
The documentation for Creating an Event Type should state that the header `Content-Type` is needed in order to execute a valid request.

`curl -v  -H "Content-Type: application/json" -XPOST http://localhost:8080/event-types -d '{
  "name": "order_received",
  "owning_application": "acme-order-service",
  "category": "business",
  "partition_strategy": "random",
  "enrichment_strategies": ["metadata_enrichment"],
  "schema": {
    "type": "json_schema",
    "schema": "{ \"properties\": { \"order_number\": { \"type\": \"string\" } } }"
  }
}'`

**Comment by lmontrieux** [comment]
Fixed and merged to master.
