### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by wontheone1** [zalando/nakadi-manual#63]
In the page for [Consuming events(high level api)](https://zalando-nakadi.github.io/nakadi-manual/docs/using/consuming-events-hila.html), the link for swagger is broken as in following sentence

> For a more detailed description and advanced configuration options please take a look at Nakadi swagger file.

And I think it is also buggy that multiple clicks of it keeps adding '/api' in the url.

**Comment by lmontrieux** [comment]
Thank you for raising this issue. We have been migrating the manual over to the nakadi repository (and website). We will soon mark this repository as abandoned, and eventually have it deleted. You can find the most up-to-date version of the documentation here: https://zalando.github.io/nakadi/manual.html

**Comment by lmontrieux** [comment]
That said, it's also broken in the new version. I will open an issue there.
